import React, { useState, useEffect } from 'react';
import Navbar from '../components/Navbar';
import JobCard from '../components/JobCard';
import jsPDF from 'jspdf';
import api from '../api/axios';

const emptyForm = {
  companyName: '', role: '', status: 'APPLIED', appliedDate: '', notes: ''
};

function Dashboard() {
  const [jobs, setJobs] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [editId, setEditId] = useState(null);
  const [filterStatus, setFilterStatus] = useState('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [quickUrl, setQuickUrl] = useState('');
  const [quickLoading, setQuickLoading] = useState(false);

  useEffect(() => {
    fetchJobs();
  }, []);

  const fetchJobs = async () => {
    const res = await api.get('/api/jobs');
    setJobs(res.data);
  };

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSave = async () => {
    if (editId) {
      await api.put(`/api/jobs/${editId}`, form);
    } else {
      await api.post('/api/jobs', form);
    }
    setForm(emptyForm);
    setEditId(null);
    setShowForm(false);
    fetchJobs();
  };

  const handleEdit = (job) => {
    setForm({
      companyName: job.companyName,
      role: job.role,
      status: job.status,
      appliedDate: job.appliedDate,
      notes: job.notes || ''
    });
    setEditId(job.id);
    setShowForm(true);
  };

  const handleDelete = async (id) => {
    await api.delete(`/api/jobs/${id}`);
    fetchJobs();
  };

  //pdf export
  const exportToPDF = () => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(108, 99, 255);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('SmartHire - Job Application Report', 14, 20);

    // Date and stats
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 40);
    doc.text(`Total Applications: ${jobs.length}`, 14, 47);

    // Summary boxes
    doc.setFillColor(240, 240, 255);
    doc.rect(14, 52, 40, 16, 'F');
    doc.rect(58, 52, 40, 16, 'F');
    doc.rect(102, 52, 40, 16, 'F');
    doc.rect(146, 52, 40, 16, 'F');

    doc.setFontSize(9);
    doc.setTextColor(108, 99, 255);
    doc.setFont('helvetica', 'bold');
    doc.text(`Applied: ${stats.applied}`, 18, 61);
    doc.text(`Interview: ${stats.interview}`, 62, 61);
    doc.text(`Offer: ${stats.offer}`, 106, 61);
    doc.text(`Rejected: ${stats.rejected}`, 150, 61);

    // Divider
    doc.setDrawColor(108, 99, 255);
    doc.setLineWidth(0.5);
    doc.line(14, 74, 196, 74);

    // Jobs list
    let y = 82;
    doc.setFont('helvetica', 'normal');

    jobs.forEach((job, index) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      // Job number and company
      doc.setFontSize(12);
      doc.setTextColor(108, 99, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(`#${index + 1}  ${job.companyName}`, 14, y);

      // Status badge color
      const statusColors = {
        'APPLIED': [30, 58, 95],
        'INTERVIEW': [59, 47, 110],
        'OFFER': [20, 83, 45],
        'REJECTED': [76, 29, 29],
      };
      const color = statusColors[job.status] || [100, 100, 100];
      doc.setFillColor(...color);
      doc.roundedRect(160, y - 6, 30, 8, 2, 2, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text(job.status, 162, y);

      // Role
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', 'normal');
      doc.text(`Role: ${job.role}`, 14, y + 7);

      // Date
      doc.text(`Applied: ${job.appliedDate || 'N/A'}`, 14, y + 14);

      // Notes
      if (job.notes) {
        doc.setTextColor(120, 120, 120);
        doc.setFontSize(9);
        const notes = job.notes.length > 80 ? job.notes.substring(0, 80) + '...' : job.notes;
        doc.text(`Notes: ${notes}`, 14, y + 21);
        y += 28;
      } else {
        y += 22;
      }

      // Divider between jobs
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.2);
      doc.line(14, y, 196, y);
      y += 6;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by SmartHire — Track Your Career Journey', 14, 290);

    doc.save(`SmartHire_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handleQuickAdd = async () => {
    if (!quickUrl) return;
    setQuickLoading(true);

    try {
      // URL se domain nikalo — company name banao
      const url = new URL(quickUrl);
      const domain = url.hostname.replace('www.', '');

      // Platform detect karo
      let companyName = '';
      let platformNote = '';

      if (domain.includes('internshala')) {
        platformNote = 'Applied via Internshala';
        companyName = ''; // User khud bharega
      }else if (domain.includes('naukri')) {
        platformNote = 'Applied via Naukri';
        const pathParts = url.pathname.split('/');
        companyName = pathParts[1] ? pathParts[1].replace(/-/g, ' ') : 'Unknown Company';
      } else if (domain.includes('linkedin')) {
        platformNote = 'Applied via LinkedIn';
        companyName = 'LinkedIn Job';
      } else if (domain.includes('indeed')) {
        platformNote = 'Applied via Indeed';
        companyName = 'Indeed Job';
      } else if (domain.includes('glassdoor')) {
        platformNote = 'Applied via Glassdoor';
        companyName = 'Glassdoor Job';
      } else {
        companyName = domain;
        platformNote = `Applied via ${domain}`;
      }

      // Form pre-fill karo
      setForm({
        companyName: companyName,
        role: '',
        status: 'APPLIED',
        appliedDate: new Date().toISOString().split('T')[0],
        notes: `${platformNote} | URL: ${quickUrl}`
      });
      setQuickUrl('');
      setShowForm(true);
      setEditId(null);

    } catch (err) {
      alert('Invalid URL! Please paste a valid job URL.');
    }
    setQuickLoading(false);
  };

  const needsFollowUp = (job) => {
    if (job.status !== 'APPLIED') return false;
    const applied = new Date(job.appliedDate);
    const today = new Date();
    const diff = Math.floor((today - applied) / (1000 * 60 * 60 * 24));
    return diff >= 7;
  };

  const filteredJobs = jobs
      .filter(job => filterStatus === 'ALL' || job.status === filterStatus)
      .filter(job => job.companyName.toLowerCase().includes(searchQuery.toLowerCase()) ||
          job.role.toLowerCase().includes(searchQuery.toLowerCase()));

  const stats = {
    total: jobs.length,
    applied: jobs.filter(j => j.status === 'APPLIED').length,
    interview: jobs.filter(j => j.status === 'INTERVIEW').length,
    offer: jobs.filter(j => j.status === 'OFFER').length,
    rejected: jobs.filter(j => j.status === 'REJECTED').length,
  };

  return (
      <div className="app-layout">
        <Navbar />
        <div className="main-content">
          <div className="dashboard">

            {/* Stats Cards */}
            <div className="stats-grid">
              <div className="stat-card total">
                <h3>{stats.total}</h3>
                <p>Total Applications</p>
              </div>
              <div className="stat-card applied">
                <h3>{stats.applied}</h3>
                <p>Applied</p>
              </div>
              <div className="stat-card interview">
                <h3>{stats.interview}</h3>
                <p>Interviews</p>
              </div>
              <div className="stat-card offer">
                <h3>{stats.offer}</h3>
                <p>Offers</p>
              </div>
              <div className="stat-card rejected">
                <h3>{stats.rejected}</h3>
                <p>Rejected</p>
              </div>
            </div>

            {/* Header */}
            <div className="dashboard-header">
              <h2>My Job Applications 💼</h2>
              <div style={{ display: 'flex', gap: '1rem' }}>
                <button className="export-btn" onClick={exportToPDF}>
                  📄 Export PDF
                </button>
              <button className="add-btn" onClick={() => {
                setShowForm(true);
                setEditId(null);
                setForm(emptyForm);
              }}>
                + Add Job
              </button>
              </div>
            </div>
            {/* Quick Add */}
            <div className="quick-add-section">
              <h3>⚡ Quick Add from Job URL</h3>
              <div className="quick-add-row">
                <input
                    className="search-input"
                    type="text"
                    placeholder="Paste job URL from Internshala, Naukri, LinkedIn, Indeed..."
                    value={quickUrl}
                    onChange={(e) => setQuickUrl(e.target.value)}
                />
                <button
                    className="add-btn"
                    onClick={handleQuickAdd}
                    disabled={quickLoading}
                >
                  {quickLoading ? 'Loading...' : '⚡ Quick Add'}
                </button>
              </div>
            </div>

            {/* Search + Filter */}
            <div className="search-filter">
              <input
                  className="search-input"
                  type="text"
                  placeholder="🔍 Search by company or role..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
              />
              <div className="filter-buttons">
                {['ALL', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED'].map(status => (
                    <button
                        key={status}
                        className={`filter-btn ${filterStatus === status ? 'active' : ''}`}
                        onClick={() => setFilterStatus(status)}
                    >
                      {status}
                    </button>
                ))}
              </div>
            </div>

            {/* Add/Edit Form */}
            {showForm && (
                <div className="job-form">
                  <h3>{editId ? 'Edit Job' : 'Add New Job'}</h3>
                  <input name="companyName" placeholder="Company Name" value={form.companyName} onChange={handleChange} />
                  <input name="role" placeholder="Role" value={form.role} onChange={handleChange} />
                  <select name="status" value={form.status} onChange={handleChange}>
                    <option value="APPLIED">APPLIED</option>
                    <option value="INTERVIEW">INTERVIEW</option>
                    <option value="OFFER">OFFER</option>
                    <option value="REJECTED">REJECTED</option>
                  </select>
                  <input name="appliedDate" type="date" value={form.appliedDate} onChange={handleChange} />
                  <input name="notes" placeholder="Notes (optional)" value={form.notes} onChange={handleChange} />
                  <div className="form-buttons">
                    <button className="save-btn" onClick={handleSave}>Save</button>
                    <button className="cancel-btn" onClick={() => setShowForm(false)}>Cancel</button>
                  </div>
                </div>
            )}

            {/* Jobs Grid */}
            {filteredJobs.length === 0 ? (
                <p className="empty-state">No job applications found. Click "+ Add Job" to get started! 🚀</p>
            ) : (
                <div className="jobs-grid">
                  {filteredJobs.map(job => (
                      <JobCard
                          key={job.id}
                          job={job}
                          onEdit={handleEdit}
                          onDelete={handleDelete}
                          needsFollowUp={needsFollowUp(job)}
                      />
                  ))}
                </div>
            )}

          </div>
        </div>
      </div>
  );
}

export default Dashboard;