# Application name
spring.application.name=smarthire

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:smarthiredb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.web.resources.static-locations=classpath:/static/
# H2 Console (browser mein database dekh sakte ho)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false
# JWT Secret Key
jwt.secret=smarthire-super-secret-key-for-jwt-token-generation-minimum-256-bits

# Server Port
server.port=8080